include:
  - project: $_GITLAB_TEMPLATES_REPO
    ref: $_GITLAB_TEMPLATES_REF
    file:
      - "/includes/include.drupalci.main.yml"
      - "/includes/include.drupalci.variables.yml"
      - "/includes/include.drupalci.workflows.yml"
composer-lint:
  allow_failure: false
cspell:
  allow_failure: false
eslint:
  allow_failure: false
phpcs:
  allow_failure: false
phpstan:
  allow_failure: false
phpunit:
  allow_failure: false
